### ISSUE TITLE
Host Material Icons Font locally instead from Google Fonts

### ISSUE THREAD

**Issue by jakob-p** [IPS-LMU/WebSpeechRecorderNg#17]
Could we add the Material Icons Font to the package instead loading it from Google Fonts?

**Comment by MJochim** [comment]
@klausj Maybe I can save you some research here. I have done exactly this in another project in the following commit:

https://github.com/MJochim/conference-registration/commit/934b1513946a468a0f9824240fe762a3cac72a18

Google explicitly allows this, they have released the font under Apache License 2.0 (see http://google.github.io/material-design-icons/).

You basically have to replace this line:

https://github.com/IPS-LMU/WebSpeechRecorderNg/blob/955deab72714ce9eaaafddda11ce281721a0f4fe/src/index.html#L10

and download a couple of files from the Google link above. You can check my old commit to see which files I downloaded and added to my own repository.

**Comment by klausj** [comment]
The library should only be used as a dependency in your own Angular project, in which you can add the Material Icons Font to host it on your own server.
